databases:
  leveling:
    credentials:
      user: "root"
      pass: ""
    host: "localhost"
    dbName: "minecraft"
    port: 3306
hydra:
  host: "redishost"
  port: 8080
  pass: "redispassword"
  enable: false