# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        distribution: 'zulu'

    - name: Run all JUnit tests
      run: gradle test
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.TOKEN }}
